#!/bin/sh
tag=$1
shift

case "$tag" in
    "debian")
        tag="debian:latest"
        ;;
    "jessie")
        tag="debian:jessie"
        ;;
    "sid")
        tag="debian:sid"
        ;;
    "ubuntu")
        tag="ubuntu:latest"
        ;;
    "precise")
        tag="ubuntu:precise"
        ;;
    "trusty")
        tag="ubuntu:trusty"
        ;;
    "utopic")
        tag="ubuntu:utopic"
        ;;
    "xenial")
        tag="ubuntu:xenial"
        ;;
    "bionic")
        tag="ubuntu:bionic"
        ;;
esac

docker build \
    --build-arg tag=$tag \
    -t \
    dm-$tag \
    .
docker run --rm -it -v "${PWD}/output:/out" dm-$tag $@
