#!/bin/sh
tag=$1
shift

case "$tag" in
    "debian")
        tab="debian:lates"
        ;;
    "ubuntu")
        tag="ubuntu:latest"
        ;;
    "precise")
        tag="ubuntu:precise"
        ;;
    "trusty")
        tag="ubuntu:trusty"
        ;;
    "xenial")
        tag="ubuntu:xenial"
        ;;
esac

docker build \
    --build-arg tag=$tag \
    -t \
    precise-make \
    .
docker run --rm -it -v "${PWD}/output:/out" precise-make $@
